java_sources(
    dependencies=[
        # Resource dependencies cannot be inferred, so we must explicitly declare that we
        # depend on them.
        "src/resources/org/pantsbuild/example/lib",
    ],
)
